import express from 'express';
import router from './routes';
import cors from 'cors';
import path from 'path';
import { errors } from 'celebrate';
const app = express();
app.use(cors());
app.use(express.json());
app.use(router);
app.use('/uploads', express.static(path.resolve(__dirname, '..', 'uploads')));
app.use('/useruploads', express.static(path.resolve(__dirname, '..', 'useruploads')));
app.use(errors());
app.listen(6464);